### ISSUE TITLE
Организация кода

### ISSUE THREAD

**Issue by ghost** [Adhol/ctshopapp#2]
Предлагается исправить структуру проекта следующим образом:
1. переименовать com.ardecs.ctshopapp -> com.ardecs.ctshop
1. ввести новые пакеты:
```
    com.ardecs.ctshop
                 +- config
                 +- persistence 
                  |     +- entity
                  |     |    +- классы хранимых сущностей
                  |     +- repository
                  |          +- классы репозиториев Spring Data
                 +- service
                 +- controller
```
1. `CTShopScript.sql` должен быть перенесен в, например, resources, отдельный каталог

**Comment by AlekseyKholmogorov** [comment]
done

**Comment by ghost** [comment]
@Adhol ,

 тут ошибочка вышла с "Java Persistence". Давай просто оставим "persistence".
В остальном выглядит хорошо.
