### ISSUE TITLE
Правки в именованиях

### ISSUE THREAD

**Issue by ghost** [Adhol/ctshopapp#3]
1. https://github.com/Adhol/ctshopapp/blob/0bbfec2d27bcb365d27879d5388a9336d235d9ef/src/main/java/com/ardecs/ctshopapp/accessingdatamysql/U_order.java#L8
нарушение правил именования. Предложение  - UserOrder
1. https://github.com/Adhol/ctshopapp/blob/0bbfec2d27bcb365d27879d5388a9336d235d9ef/src/main/java/com/ardecs/ctshopapp/accessingdatamysql/repo/U_orderRepo.java#L6
нарушение правил именования. Предложение  - UserOrderRepository
1. https://github.com/Adhol/ctshopapp/blob/0bbfec2d27bcb365d27879d5388a9336d235d9ef/src/main/java/com/ardecs/ctshopapp/accessingdatamysql/Category.java#L12
достаточно `id`
1. https://github.com/Adhol/ctshopapp/blob/0bbfec2d27bcb365d27879d5388a9336d235d9ef/src/main/java/com/ardecs/ctshopapp/CtshopappApplication.java#L7
достаточно `Application`
1. https://github.com/Adhol/ctshopapp/blob/0bbfec2d27bcb365d27879d5388a9336d235d9ef/src/main/java/com/ardecs/ctshopapp/accessingdatamysql/User.java#L22
достаточно `orders`

**Comment by malahov86** [comment]
От себя добавлю - относится не только к полям, но и к названию методов, нужно соблюдать код конвенцию
https://www.oracle.com/technetwork/java/codeconvtoc-136057.html

**Comment by AlekseyKholmogorov** [comment]
done
