### ISSUE TITLE
Проблема в тестах

### ISSUE THREAD

**Issue by ghost** [Adhol/ctshopapp#4]
Тесты не выполняются корректно при сборке приложения.
Предложения:
1. использовать БД в памяти для тестов; завести отдельны профель дл них
1. создавать структуру БД из имеющегося файла (аннотация @Sql ?)
1. https://github.com/Adhol/ctshopapp/blob/0bbfec2d27bcb365d27879d5388a9336d235d9ef/src/test/java/com/ardecs/ctshopapp/CtshopappApplicationTests.java#L42-L46
тест не имеет смысла - он ничего не проверят

**Comment by malahov86** [comment]
Согласен, для того чтобы запустить тесты нужно устанавливать и настраивать БД - лучше использовать H2 db

**Comment by AlekseyKholmogorov** [comment]
done
