### ISSUE TITLE
Ошибка в скрипте

### ISSUE THREAD

**Issue by malahov86** [Adhol/ctshopapp#5]
https://github.com/Adhol/ctshopapp/blob/0bbfec2d27bcb365d27879d5388a9336d235d9ef/src/main/java/com/ardecs/ctshopapp/accessingdatamysql/mySqlScript/CTShopScript.sql#L46-L49

Нужно добавить в конце точку с запятой, иначе скрипт упадет.

**Comment by AlekseyKholmogorov** [comment]
done
